package com.cmp.pushuptracker.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFFFF6B6B)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFFFDADB)
val OnPrimaryContainerLight = Color(0xFF410005)
val SecondaryLight = Color(0xFF4ECDC4)
val OnSecondaryLight = Color(0xFF1A1F28)
val SecondaryContainerLight = Color(0xFFC7F3EE)
val OnSecondaryContainerLight = Color(0xFF003731)
val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF1A1F28)
val SurfaceLight = Color(0xFFF2F2F5)
val OnSurfaceLight = Color(0xFF1A1F28)
val ErrorLight = Color(0xFFB00020)
val OnErrorLight = Color(0xFFFFFFFF)
val SurfaceVariantLight = Color(0xFFE0E0E3)
val OutlineLight = Color(0xFF70757F)
val InverseSurfaceLight = Color(0xFF303033)
val InverseOnSurfaceLight = Color(0xFFF2F2F5)

val PrimaryDark = Color(0xFFFF6B6B)
val OnPrimaryDark = Color(0xFF1A1F28)
val PrimaryContainerDark = Color(0xFF6B2E2E)
val OnPrimaryContainerDark = Color(0xFFFFDADB)
val SecondaryDark = Color(0xFF4ECDC4)
val OnSecondaryDark = Color(0xFFFFFFFF)
val SecondaryContainerDark = Color(0xFF1E3C3A)
val OnSecondaryContainerDark = Color(0xFFC7F3EE)
val BackgroundDark = Color(0xFF1A1F28)
val OnBackgroundDark = Color(0xFFF2F2F5)
val SurfaceDark = Color(0xFF242833)
val OnSurfaceDark = Color(0xFFF2F2F5)
val ErrorDark = Color(0xFFCF6679)
val OnErrorDark = Color(0xFF1A1F28)
val SurfaceVariantDark = Color(0xFF2E3240)
val OutlineDark = Color(0xFF888D9F)
val InverseSurfaceDark = Color(0xFFF2F2F5)
val InverseOnSurfaceDark = Color(0xFF1A1F28)