package com.cmp.pushuptracker.utils

import kotlin.random.Random

val workoutQuotes = listOf(
    "The only bad workout is the one that didn't happen.",
    "Sweat is just fat crying.",
    "Push yourself because no one else is going to do it for you.",
    "Don't count the days - make the days count. - Muhammad Ali",
    "The body achieves what the mind believes.",
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. - Aristotle",
    "No pain, no gain. Shut up and train.",
    "Your only limit is you.",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Don't wish for it - work for it.",
    "It never gets easier, you just get stronger.",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Success starts with self-discipline.",
    "Train insane or remain the same.",
    "Your body can stand almost anything. It's your mind you have to convince.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "Wake up with determination. Go to bed with satisfaction.",
    "What seems impossible today will one day become your warm-up.",
    "The difference between try and triumph is a little \"umph.\" - Marvin Phillips",
    "Be stronger than your strongest excuse.",
    "Don't limit your challenges - challenge your limits.",
    "You don't get what you wish for - you get what you work for.",
    "Exercise is a celebration of what your body can do, not a punishment for what you ate.",
    "A year from now you may wish you had started today. - Karen Lamb",
    "When you feel like quitting, think about why you started.",
    "Every workout is progress.",
    "Good things come to those who sweat.",
    "If it doesn't challenge you, it won't change you.",
    "Strength does not come from the body. It comes from the will. - Mahatma Gandhi",
    "Fall in love with taking care of yourself.",
    "Your health is an investment, not an expense.",
    "Keep going. Everything you need will come to you at the perfect time.",
    "The gym is my therapy.",
    "Strive for progress, not perfection.",
    "One workout at a time - one day at a time.",
    "Energy and persistence conquer all things. - Benjamin Franklin",
    "Great things never came from comfort zones.",
    "It's you vs. you.",
    "Discipline is choosing between what you want now and what you want most. - Abraham Lincoln",
    "Do something today that your future self will thank you for.",
    "Champions keep playing until they get it right. - Billie Jean King",
    "The only bad session is the one you skip.",
    "Your hardest times often lead to the greatest moments of your life.",
    "Fitness is not about being better than someone else - it's about being better than you used to be.",
    "Stop wishing. Start doing.",
    "Don't stop when you're tired - stop when you're done.",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "A little progress each day adds up to big results.",
    "Work hard in silence. Let success be your noise.",
    "Excuses don't burn calories.",
    "Pain is temporary. Quitting lasts forever. - Lance Armstrong",
    "Your body is your most priceless possession - take care of it.",
    "Motivation gets you started. Habit keeps you going.",
    "Be proud, but never satisfied.",
    "The best project you'll ever work on is you.",
    "Fitness is like a relationship - you can't cheat and expect it to work.",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "If you still look good at the end of your workout, you didn't train hard enough.",
    "Success isn't always about greatness. It's about consistency.",
    "You are one workout away from a good mood.",
    "Don't wish for a good body. Work for it.",
    "It's going to be a journey. It's not a sprint to get in shape.",
    "Fitness is not a destination - it's a way of life.",
    "Suck it up and one day you won't have to suck it in.",
    "There is no substitute for hard work. - Thomas Edison",
    "The real workout starts when you want to stop.",
    "Push-ups don't lie.",
    "Your future self will thank you for what you start today.",
    "Fall in love with the process, and the results will come.",
    "You are stronger than you think.",
    "Action is the foundational key to all success. - Pablo Picasso",
    "The pain of discipline is less than the pain of regret.",
    "Health is the real wealth.",
    "Train hard. Turn heads.",
    "Winners train, losers complain.",
    "Stronger than yesterday.",
    "Conquer from within.",
    "Good things come to those who sweat.",
    "Falling down is an accident. Staying down is a choice.",
    "Don't stop when you're tired. Stop when you're done.",
    "Fit is not a destination; it's a way of life.",
    "The best time to work out is now.",
    "Pain is weakness leaving the body.",
    "The harder you work, the luckier you get. - Gary Player",
    "Earn your shower.",
    "Don't count the weights - lift the counts.",
    "When in doubt, work out.",
    "Your only competition is who you were yesterday.",
    "Fitness is the gateway to a healthier, happier you.",
    "Beat your best.",
    "The body achieves what the mind believes.",
    "Life has its ups and downs - we call them squats.",
    "Exercise to be fit, not skinny.",
    "Build the body you want, one rep at a time.",
    "Don't limit yourself. You are capable of more.",
    "Tonight's workout will be tomorrow's strength.",
    "Mind over matter.",
    "Progress: one more rep than yesterday.",
    "Train like a beast, look like a beauty."
)

fun getRandomQuote(): String {
    val quotes = workoutQuotes
    if (quotes.isEmpty()) return ""
    return quotes[Random.nextInt(quotes.size)]
}